<a href="https://colab.research.google.com/github/mantis2404/ML-Exercises/blob/main/Fine_Tuning_RL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
  %pip install datasets > /dev/null 2>&1
  %pip install tokenizers > /dev/null 2>&1
  %pip install torch tensorboard > /dev/null 2>&1
  %pip install transformers datasets accelerate evaluate trl protobuf sentencepiece > /dev/null 2>&1
  %pip install peft > /dev/null 2>&1
  %pip install -U bitsandbytes > /dev/null 2>&1

In [ ]:
  from google.colab import userdata
  from huggingface_hub import login
  from trl import SFTConfig, GRPOTrainer, SFTTrainer

  from peft import prepare_model_for_kbit_training
  import pandas as pd
  import numpy as np
  import torch
  from transformers import AutoTokenizer, AutoModelForCausalLM
  from transformers import pipeline
  from torch.utils.data import DataLoader

  from random import randint
  from datasets import Dataset
  import pandas as pd
  import os
  from peft import LoraConfig, get_peft_model
  from peft import LoraConfig
  from trl import AutoModelForCausalLMWithValueHead

  from transformers import AutoModelForSequenceClassification
  from trl import GRPOTrainer, GRPOConfig
  from transformers import AutoTokenizer, AutoModelForCausalLM
  from transformers import pipeline
  from sentence_transformers import SentenceTransformer, util
  import re

# Login into Hugging Face Hub
# hf_token = userdata.get('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') # If you are running inside a Google Colab

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
login(token='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')
base_model = "google/gemma-3-270m-it"
# checkpoint_dir = "/content/drive/MyDrive/EthosML"

In [ ]:
import pandas as pd
df=pd.read_csv('./train.csv');

In [ ]:
df.head(1)

,topic,problem_statement,solution,answer_option_1,answer_option_2,answer_option_3,answer_option_4,answer_option_5,correct_option_number
0,Optimization of actions and planning,Maria needs to prepare for a party and has lim...,Maria should first prepare the cake and put it...,"Bake the cake, decorate the living room, pick ...","Decorate the living room, bake the cake, pick ...","Pick up friend, bake the cake, decorate the li...","Bake the cake, decorate the living room, pick ...",Another answer,4

In [ ]:

def create_conversation(sample):
  return {
    "messages": [
        {
            "role": "user",
            "content": (
                f"Topic: {sample['topic']}\n"
                f"Question: {sample['problem_statement']}\n"
                f"Options:\n"
                f"1) {sample['answer_option_1']}\n"
                f"2) {sample['answer_option_2']}\n"
                f"3) {sample['answer_option_3']}\n"
                f"4) {sample['answer_option_4']}\n"
                f"5) {sample['answer_option_5']}\n"
                "Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks."
            )
        },
        {
            "role": "assistant",
            "content": (
                f"Correct Answer: {sample['correct_option_number']})\n"
                f"Reasoning:\n{sample['solution']}"
            )
        }
    ]
}

hf_dataset = Dataset.from_pandas(df)

# Now you can map your function safely
hf_dataset = hf_dataset.map(create_conversation, remove_columns=hf_dataset.column_names, batched=False)

# Split dataset into 80% training samples and 20% test samples
hf_dataset = hf_dataset.train_test_split(test_size=0.2, shuffle=False)

# Print formatted user prompt
print(hf_dataset["train"][0]["messages"])

Map:   0%|          | 0/384 [00:00<?, ? examples/s]

[{'content': 'Topic: Optimization of actions and planning\nQuestion: Maria needs to prepare for a party and has limited time. She has to bake a cake that takes 1 hour to prepare and bake, decorate her living room which takes 1.5 hours, and pick up a friend from the airport which is 30 minutes away. Maria can decorate the living room while the cake is baking but she cannot leave for the airport if the cake is still in the oven. What is the most efficient sequence of actions for Maria to finish all tasks and what is the minimum total time needed if she starts at 1 PM and must finish all tasks by 4 PM?\nOptions:\n1) Bake the cake, decorate the living room, pick up friend; 3.5 hours\n2) Decorate the living room, bake the cake, pick up friend; 4 hours\n3) Pick up friend, bake the cake, decorate the living room; 3 hours\n4) Bake the cake, decorate the living room, pick up friend; 2.5 hours\n5) Another answer\nWhich one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.', 'role': 'user'}, {'content': 'Correct Answer: 4)\nReasoning:\nMaria should first prepare the cake and put it in the oven. While the cake is baking, she can decorate the living room. This takes 1 hour, and the cake will be done at the same time. Then Maria can go to the airport to pick up her friend. The trip to the airport and back takes 1 hour in total, so if she begins at 1 PM, she will be done with all tasks by 3:30 PM.', 'role': 'assistant'}]

In [ ]:
print(hf_dataset)

DatasetDict({
    train: Dataset({
        features: ['messages'],
        num_rows: 307
    })
    test: Dataset({
        features: ['messages'],
        num_rows: 77
    })
})

In [ ]:

model = AutoModelForCausalLM.from_pretrained(
    base_model,
    torch_dtype="auto",
    device_map="auto",
    attn_implementation="eager"
)

tokenizer = AutoTokenizer.from_pretrained(base_model)
pipe = pipeline("text-generation", model=model, tokenizer=tokenizer)

# # Define a simple chat template (required)
# tokenizer.chat_template = """{% for message in messages %}
# {{'<|user|> ' + message['content'] if message['role'] == 'user' else '<|assistant|> ' + message['content']}}
# {% endfor %}{{ '<|assistant|>' if add_generation_prompt }}"""

# Load a random sample from the test dataset
rand_idx = randint(0, len(hf_dataset["test"])-1)
test_sample = hf_dataset["test"][rand_idx]

# Convert as test example into a prompt with the model template
prompt = pipe.tokenizer.apply_chat_template(test_sample["messages"][:1], tokenize=False, add_generation_prompt=True)
outputs = pipe(prompt, max_new_tokens=256, disable_compile=True)


# generated_text = outputs[0]["generated_text"]
# assistant_marker = "<|assistant|>"
# start_idx = generated_text.find(assistant_marker)

# if start_idx != -1:
#     generated_answer = generated_text[start_idx + len(assistant_marker):].strip()
# else:
#     generated_answer = generated_text[len(prompt):].strip()

# Extract the user query and original answer
print(f"Question:\n{test_sample['messages'][0]['content']}\n")
print(f"Original Answer:\n{test_sample['messages'][1]['content']}\n")
print(f"Generated Answer (base model):\n{outputs[0]['generated_text'][len(prompt):].strip()}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/1.35k [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/536M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/173 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.69M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

KeyboardInterrupt:

### SFT(SUPERVISED FINE TUNING)

In [ ]:
from trl import SFTConfig

torch_dtype = model.dtype

args = SFTConfig(
    output_dir="./stf_model",              # directory to save and repository id
    max_length=512,                         # max sequence length for model and packing of the dataset
    packing=False,                          # Groups multiple samples in the dataset into a single sequence
    num_train_epochs=5,                     # number of training epochs
    per_device_train_batch_size=4,          # batch size per device during training
    gradient_checkpointing=False,           # Caching is incompatible with gradient checkpointing
    optim="adamw_torch_fused",              # use fused adamw optimizer
    logging_steps=1,                        # log every step
    save_strategy="epoch",                  # save checkpoint every epoch
    eval_strategy="epoch",                  # evaluate checkpoint every epoch
    learning_rate=learning_rate,            # learning rate
    fp16=True if torch_dtype == torch.float16 else False,   # use float16 precision
    bf16=True if torch_dtype == torch.bfloat16 else False,  # use bfloat16 precision
    lr_scheduler_type="constant",           # use constant learning rate scheduler
    push_to_hub=False,                      # push model to hub
    report_to="none",
    dataset_kwargs={
        "add_special_tokens": False, # Template with special tokens
        "append_concat_token": True, # Add EOS token as separator token between examples
    }
)

In [ ]:


# Create Trainer object
trainer = SFTTrainer(
    model=model,
    args=args,
    train_dataset=hf_dataset['train'],
    eval_dataset=hf_dataset['test'],
    processing_class=tokenizer,
)

Tokenizing train dataset:   0%|          | 0/307 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/307 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/77 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/77 [00:00<?, ? examples/s]

In [ ]:
trainer.train()

TrainOutput(global_step=385, training_loss=0.7959404182124448, metrics={'train_runtime': 880.9957, 'train_samples_per_second': 1.742, 'train_steps_per_second': 0.437, 'total_flos': 378895847022336.0, 'train_loss': 0.7959404182124448, 'epoch': 5.0})

In [ ]:
# model = HuggingFace.from_pretrained("meta-llama/Llama-3.1-8B-Instruct")
!zip -r sft_model.zip ./stf_model

In [ ]:
model_id = "./stf_model/checkpoint-385"

# Load Model
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype="auto",
    device_map="auto",
    attn_implementation="eager"
)
tokenizer = AutoTokenizer.from_pretrained(model_id)

pipe = pipeline("text-generation", model=model, tokenizer=tokenizer)

def test(test_sample):
  # Convert as test example into a prompt with the Gemma template
  prompt = pipe.tokenizer.apply_chat_template(test_sample["messages"][:1], tokenize=False, add_generation_prompt=True)
  outputs = pipe(prompt, max_new_tokens=256, disable_compile=True)

  # Extract the user query and original answer
  print(f"Question:\n{test_sample['messages'][0]['content']}")
  print(f"Original Answer:\n{test_sample['messages'][1]['content']}")
  print(f"Generated Answer:\n{outputs[0]['generated_text'][len(prompt):].strip()}")
  print("-"*80)

# Test with an unseen dataset
for item in hf_dataset['test']:
  test(item)

Device set to use cuda:0

Question:
Topic: Sequence solving
Question: You are given a sequence of numbers where each number represents an action. The actions are defined as follows: 1-Add 3, 2-Subtract 2, 3-Multiply by 5, and 4-Divide by 2. Starting with the number 10, follow the sequence of actions 2, 1, 3, 2, 4, 1. What is the result after performing all these actions in the given order?
Options:
1) 27.5
2) 29.5
3) 32.5
4) 34.5
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
Starting with the number 10, follow each action step by step:
- Step 1 (2): 10 - 2 = 8
- Step 2 (1): 8 + 3 = 11
- Step 3 (3): 11 * 5 = 55
- Step 4 (2): 55 - 2 = 53
- Step 5 (4): 53 / 2 = 26.5
- Step 6 (1): 26.5 + 3 = 29.5
Hence, the result after following the actions in the given order is 29.5.
Generated Answer:
Correct Answer: 5)
Reasoning:
To solve this sequence, you would perform the actions in the order of increasing magnitude: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, which is the sequence of the natural numbers. Therefore, the final number is 10.5.
--------------------------------------------------------------------------------
Question:
Topic: Sequence solving
Question: Alice has created a sequence where each number is generated by adding the square of the number's position in the sequence (where the first position is 1, the second position is 2, and so on) to the previous number. If the sequence starts with 1, what is the 6th number in the sequence?
Options:
1) 81
2) 66
3) 77
4) 91
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 4)
Reasoning:
The sequence starts with 1. To generate subsequent numbers, we add the square of the position number to the previous value: 2nd number: 1 + 2^2 = 5 3rd number: 5 + 3^2 = 14 4th number: 14 + 4^2 = 30 5th number: 30 + 5^2 = 55 6th number: 55 + 6^2 = 91 Thus, the 6th number in the sequence is 91.
Generated Answer:
Correct Answer: 3)
Reasoning:
To solve the sequence, we use the rule: the position of the number in the sequence is directly related to its position in the sequence. The first number is 1, so its position is 1. The next number will be calculated by adding the position to the previous number (1+2=3). For 2, the next number will be 3+2=5. For 3, the next number will be 5+3=8. For 4, the next number will be 8+4=16. For 5, the next number will be 16+5=21. So, the 6th number is 21.
--------------------------------------------------------------------------------
Question:
Topic: Logical traps
Question: Alice, Bob, and Charlie are participants in a game show. The host shows them five hats: three red and two blue. Each participant is blindfolded and has one hat placed on their head; the remaining hats are hidden. They can't see their own hat, but they can see the hats of the other two participants. The first to correctly announce the color of their own hat wins a prize. Alice sees that Bob and Charlie have red hats. Bob sees that Alice and Charlie have red hats. Charlie sees that Alice and Bob have red hats. They all deduce logically and do not guess. Alice says she doesn't know the color of her hat. Bob also says he doesn't know the color of his hat. Charlie then announces the color of his hat. What color is Charlie's hat, and what is the logical explanation?
Options:
1) Red
2) Blue
3) The color cannot be determined
4) Not enough information
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
Charlie's hat is red. Since Alice sees two red hats, if her hat were blue, Bob would see one red and one blue hat. In that case, knowing there are only two blue hats, Bob would deduce that his hat must be red. However, Bob didn't know the color of his hat, which means Alice's hat must be red. Bob sees two red hats as well, and if his hat were blue, following the same logic as before, Charlie would have answered without waiting for Bob to speak. Since Charlie also didn't know until Bob spoke, it means all three participants are wearing red hats.
Generated Answer:
Correct Answer: 4)
Reasoning:
Bob and Charlie's hats must both be red. Since Alice can see Bob and Charlie have red hats, she must also have a red hat on her head. If Alice and Charlie's hats were red, then Charlie would have to have a red hat on him as well, which is not possible. Therefore, Alice cannot know the color of her hat. If Alice had to deduce the color of her hat, she would know her hat must be either blue or red, which contradicts the fact that Alice can see Bob and Charlie have red hats. Therefore, Alice cannot deduce the color of her hat. However, since Bob can't deduce his hat's color, Alice cannot deduce hers. Alice and Charlie both must have a red hat on them to solve this puzzle. Therefore, Alice cannot deduce the color of her hat. If Bob had to deduce his hat's color, then Charlie must have a red hat on him, which is a logical contradiction. So, Alice cannot deduce her hat's color. Charlie must also have a red hat on him to solve the puzzle. Alice deduces that Bob and Charlie must have a red hat on them because Alice can see Bob and Charlie have red hats.
--------------------------------------------------------------------------------
Question:
Topic: Sequence solving
Question: You are given a sequence of numbers where each number is the product of the previous two numbers minus the sum of the previous two numbers plus 2: 4, 5, 14, 58, ... What is the next number in the sequence?
Options:
1) 208
2) 53
3) 77
4) 82
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 5)
Reasoning:
The next number is calculated as follows: Take the last two numbers from the given sequence, multiply them and then subtract their sum before adding 2. If the last two numbers are 5 and 14, their product is 70. We then subtract the sum of 5 and 14, which is 19, from 70 to get 51. Finally, we add 2, resulting in the next number being 53. Using this method, following the sequence starting with 4 and 5, we get: (4*5 - (4+5) + 2) = 14, (5*14 - (5+14) + 2) = 58, (14*58 - (14+58) + 2) = 53. Therefore, the next number is 53.
Generated Answer:
Correct Answer: 5)
Reasoning:
The sequence follows a pattern based on the rule (or a similar one) that the sum of the previous two numbers and the absolute value of the previous number (starting from 1) should result in the next number. Starting from 1, the next number is calculated by multiplying 1 by itself, then adding the position of the term (starting from 1) to get the position in the sequence, and then adding the absolute value of that position (starting from 1) to correct the result. So, 5*1+1=6 or 5+6=11.
--------------------------------------------------------------------------------
Question:
Topic: Operation of mechanisms
Question: In a certain mechanical workshop, there are three machines that can only operate one at a time due to limited electrical capacity. Machine A takes 3 hours to complete its job. Machine B takes 4 hours, and Machine C takes 6 hours. They all need to complete one job each. The workshop operates an 8-hour workday. If only one machine can operate at any given time and no machine can be stopped mid-operation, what is the maximum number of full days needed to complete all three jobs?
Options:
1) 1 day
2) 2 days
3) 3 days
4) 4 days
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
Machine A takes 3 hours, B takes 4 hours, and C takes 6 hours. In an 8-hour workday, you can run A and B on the first day (3+4 = 7 hours). On the second day, you can run machine C for 6 hours. Thus, the maximum number of full days needed to complete all jobs without breaking any machine's operation midway is 2 full days.
Generated Answer:
Correct Answer: 1)
Reasoning:
To maximize the number of days, the workshop should have at least two machines in the first place. Since only A can operate on a single machine, A cannot be stopped and must be used to finish the job. Hence, the first machine must be used to finish the first job. After A is used, Machine C can complete the second job. The workshop is done and the first day is over. In the last day, Machine B finishes the third job. The total number of days taken to complete all three jobs is 3 + 1 + 3 = 7 days.
--------------------------------------------------------------------------------
Question:
Topic: Spatial reasoning
Question: You are in a room with 4 doors, each door is painted with a different color; red, blue, green, and yellow. Each door leads to a room of the same color. Once you enter a colored room, there is another door that leads back to the original room which is not necessarily the same color as the one you entered. The red room leads back through the green door, the green room leads back through the red door, the blue room leads back through the yellow door. Which door leads back to the original room when you exit from the yellow room?
Options:
1) Red Door
2) Green Door
3) Blue Door
4) Yellow Door
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 3)
Reasoning:
Since the green room leads back through the red door, the red room leads back through the green door, and the blue room leads back through the yellow door, the only option left is that the yellow room leads back through the blue door.
Generated Answer:
Correct Answer: 1)
Reasoning:
When you exit the yellow room, you return to the red room. The doors then lead you to the green and the blue rooms. The red room leads you back through the green door. The blue room leads you back to the red room. The yellow room remains unchanged. Therefore, the order of doors you exit from when you exit the yellow room is Red, Green, Blue, and Yellow.
--------------------------------------------------------------------------------
Question:
Topic: Classic riddles
Question: A king has 100 bottles of wine, and one of them is poisoned. The poison is such that if ingested, the effects are visible only after 24 hours. The king needs to find the poisoned bottle by tomorrow so he can execute the culprit at a banquet. He has 10 prisoners at his disposal to act as tasters. How can the king use the prisoners to identify the poisoned bottle by the next day?
Options:
1) Assign each prisoner to drink from 10 different bottles
2) Use a binary system to minimize the number of tasters while ensuring one tasting round
3) Let each prisoner taste randomly until one of them shows the effects of poison
4) Divide the bottles into 10 groups of 10 and have each prisoner taste an entire group
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
The king can assign each bottle a number from 1 to 100 and then convert those numbers into binary. Each prisoner will be assigned a bit position, from the first (1) to the tenth (1024). For every bottle, if the number has a '1' in a prisoner's bit position, that prisoner drinks from the bottle. For example, the bottle number 3 is 0011 in binary; therefore, prisoners number 1 and 2 will drink from this bottle. If bottle number 58, which is 111010 in binary, is poisoned, prisoners 1, 2, 4, and 6 will die, and from the binary pattern, the king will know that bottle 58 is the poisoned one. This will require the least amount of prisoners and testing to find out the poisoned bottle in one go.
Generated Answer:
Correct Answer: 2)
Reasoning:
Let's consider the classic riddle 'If I were to split the 100 bottles into 100 equal parts and let one part be the poisoned bottle, which part would you choose and why?' This puzzle encourages thinking outside the traditional confines of behavioral science. The prisoners need to figure out which bottle-tasting individual is lying and then decide which of the 100 bottles to poison. It's a game-like exercise where the traps are situational and the prisoners must make informed decisions based on observed behavior.
--------------------------------------------------------------------------------
Question:
Topic: Optimization of actions and planning
Question: You have 4 tasks to complete with different priorities and durations. Task A has a duration of 4 hours with a high priority. Task B takes 1 hour with a medium priority. Task C occupies you for 3 hours with a low priority. Task D is 2 hours long with a high priority. Your challenge is to minimize the total time spent on tasks by efficiently ordering their completion based on the principle that high priority tasks can't be postponed unless a higher priority task is occupying the slot. If a task is started it must be finished before another is taken up. What is the sequence of tasks that ensures the shortest time to complete all the tasks, taking into account the given constraints?
Options:
1) A-B-C-D
2) A-D-B-C
3) D-B-A-C
4) B-A-D-C
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 3)
Reasoning:
According to the problem constraints, high priority tasks should be done first unless they are longer and a shorter medium priority task can be done in meantime. Therefore, start with Task D (high priority, 2 hours), then do Task B (medium priority, 1 hour) while waiting to begin Task A (since it's longer), and finish with Task A (high priority, 4 hours), ending with Task C (low priority, 3 hours). The sequence is D-B-A-C.
Generated Answer:
Correct Answer: 2)
Reasoning:
To minimize the time spent on tasks, you should start with Task A (duration 4 hours, high priority). Task B (duration 1 hour, medium priority) should be started as it takes less time than Task A. Then, start Task C (3 hours, low priority). Task D (2 hours, high priority) cannot be started as it would take an excessive amount of time for another task to take over. Therefore, Task C is scheduled for the last hour. The task sequence is A-B-C-D. The activities are completed in the order of D-B-A-C. The total time spent on tasks is 4 + 1 + 3 + 2 = 9 hours.
--------------------------------------------------------------------------------
Question:
Topic: Spatial reasoning
Question: You are in charge of arranging different colored cubes in a 3x3x3 cube grid. The grid must be filled so that each 1x1x1 cube touches exactly one other cube of the same color along one of its faces. You have equal numbers of red, green, and blue cubes. How many ways are there to arrange the cubes in the grid following these rules?
Options:
1) 6 ways
2) 24 ways
3) 32 ways
4) 48 ways
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 5)
Reasoning:
Each layer of the 3x3x3 cube can be considered as a separate problem. Since each cube must touch exactly one cube of the same color, each color in a layer must form an L shape. There are two possible L shapes for each color (mirrored). This can be arranged in each layer in 2 ways for each color and there are 3 layers. Since the first layer has 2^3 options, and the colors in the subsequent layers are dependent on the layer below (to prevent vertical matching), there are 3 layers giving us 2^3 * 2^2 * 2^1 = 32 unique ways to arrange the cubes.
Generated Answer:
Correct Answer: 4)
Reasoning:
There are 6 ways to arrange the cubes in a 3x3x3 cube grid. There are 27 such cubes in total. For each of the 6 faces of the cube, there are 6 options for the corner cubes. Counting the corner cubes, there are 20 options. Once all the corner cubes are placed, we need to account for the 1-cube rule. Each of the 8 corners can be paired with 1 cube in 3 ways. So there are 20 options for the 4 corner cubes. The 1-only cube can be paired with 0 cubes in 1 way. Thus, the total number of ways is 6 * 20 = 120.
--------------------------------------------------------------------------------

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Question:
Topic: Operation of mechanisms
Question: In a factory, there are three machines A, B, and C. Machine A can produce 30 widgets per hour. Machine B can produce 20 widgets more per hour than Machine A, but it's only 80% as reliable (meaning it's operational 80% of the time B operates). Machine C is two times less productive than Machine A, but it never breaks down. If all machines start working simultaneously, after 4 hours of operation, due to a power outage, only one of the machines can be operated for an additional 2 hours. Which machine should be operated after the power outage to maximize the number of widgets produced at the end of the 6-hour period, assuming that machine B, if selected, will not face any reliability issues during those additional hours?
Options:
1) Machine A
2) Machine B
3) Machine C
4) None of the machines
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
Machine A produces 30 widgets per hour. Machine B produces 50 widgets per hour (30 + 20) and is 80% reliable, so on average, it produces 40 widgets per hour (50 * 0.8). Machine C produces 15 widgets per hour. In 4 hours, A would produce 120 widgets, B would produce 160 widgets (assuming no downtime), and C would produce 60 widgets. For the next 2 hours, A would produce 60 more widgets, B would produce 100 more widgets, and C would produce 30 more widgets. Therefore, operating machine B for the additional 2 hours results in the highest number of widgets, bringing the total to 260 widgets (160 + 100).
Generated Answer:
Correct Answer: 3)
Reasoning:
To maximize the number of widgets produced, we need to find out which machine produces more widgets in 4 hours. However, since only one machine can be operated after the power outage, we need to find out which one produces the most widgets in 4 hours. Since A produces 30 widgets per hour and B produces 20 widgets more, we can find that combination by finding the ratio of their production rates. A = 1/30 of a widget per hour, B = 1/20 of a widget per hour, and C = 1/8 of a widget per hour. The ratio of production rates indicates that if A produces 1/30 widgets per hour, and B produces 1/20 widgets per hour, they will each produce 1/30 * 20 widgets (A * 4 hours) + 1/20 * 20 widgets (B * 4 hours) + 1/8 * 20 widgets (C * 4 hours) = 30/20 * 4 hours) The only ratio that gives us a whole number of widgets produced is when A and B operate together (1/
--------------------------------------------------------------------------------
Question:
Topic: Lateral thinking
Question: There is one word in the English language that is always pronounced incorrectly. What is it?
Options:
1) Wednesday
2) Incorrectly
3) Queue
4) Colonel
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
The solution to this lateral thinking puzzle is not a matter of knowledge about the language, but understanding that the question itself is a play on words. The word 'incorrectly' itself is always pronounced 'incorrectly', as that is its correct pronunciation—it is a trick question that plays on the literal meaning of the statement itself.
Generated Answer:
Correct Answer: 1)
Reasoning:
The correct word is 'incorrect.' It is a matter of pronunciation and depends on individual hearing and error detection. However, the most common and incorrect pronunciation of the word is 'incorrectly.' It means the sound isn't correct; it sounds unsure or unsure-sounding.
--------------------------------------------------------------------------------
Question:
Topic: Sequence solving
Question: Imagine a sequence where each term is the result of the multiplication of the sum of the digits of the previous term. The sequence starts with 289. What is the 4th term in the sequence?
Options:
1) 100
2) 19
3) 361
4) 1
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 5)
Reasoning:
The sequence starts with 289. The sum of digits of 289 is 2 + 8 + 9 = 19. The second term is therefore the result of 19 multiplied by itself, which is 361. Sum of digits of 361 is 3 + 6 + 1 = 10. The third term is 10 multiplied by itself, which is 100. Now, the sum of digits of 100 is 1 + 0 + 0 = 1. So, the fourth term is 1 multiplied by itself, which is 1.
Generated Answer:
Correct Answer: 5)
Reasoning:
The sequence is a Fibonacci sequence that starts with 289. The next term will be calculated using the rule: sum of its digits gives the next number. Starting from 289, the next number is calculated as 2 + 8 + 9 = 18. So, the 4th term is 18.
--------------------------------------------------------------------------------
Question:
Topic: Sequence solving
Question: In a certain number sequence, each number after the first follows a specific but simple rule based on its position and the preceding number. The sequence starts with 1 and the first six numbers are: 1, 2, 4, 7, 11, 16. What is the seventh number in the sequence?
Options:
1) 19
2) 20
3) 21
4) 22
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 4)
Reasoning:
The sequence follows a rule where each number is the sum of the preceding number and the position of that preceding number in the sequence. So the second number is 1 (the first number) + 1 (its position) = 2, the third number is 2 (the second number) + 2 (its position) = 4, and so on. Following this pattern, the seventh number is the sixth number (16) plus its position (6), which equals 22.
Generated Answer:
Correct Answer: 5)
Reasoning:
The sequence is a Fibonacci sequence that starts with 1 and each number is the sum of the two preceding numbers. For the number 2, the next number is 2 + 1 = 3. For the number 4, the next number is 4 + 7 = 13. For the number 7, the next number is 7 + 11 = 20. For the number 11, the next number is 11 + 16 = 27. Therefore, the seventh number in the sequence is 27.
--------------------------------------------------------------------------------
Question:
Topic: Spatial reasoning
Question: Imagine you're looking at a cube that has 6 faces, each face painted with a different color: red, blue, yellow, green, orange, and purple. The cube is then placed inside a completely dark room. You have a flashlight that you can shine on only one face of the cube at a time to reveal its color. What is the minimum number of faces you need to illuminate to guarantee you can determine the color of every face of the cube?
Options:
1) 2
2) 3
3) 4
4) 5
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
The minimum number of faces you need to illuminate to determine the color of every face of the cube is 3, provided you choose the right faces. If you illuminate one face, you see that color, and you automatically know the color of the opposite face cannot be any of the remaining colors you find. Then, illuminate an adjacent face to the one you already lit up (this gives you two adjacent sides). Now you have three unknown colors and two more faces to check. By illuminating another face adjacent to the first two (but not opposite the second illuminated face), you will see the third color and know which two colors are left for the remaining faces. Since the opposite faces of a cube are always the remaining two colors, you don't need to illuminate them, you will already know their colors.
Generated Answer:
Correct Answer: 1)
Reasoning:
The minimum number of faces you need to illuminate to guarantee you'll find the correct color is 1. You need to make sure you're looking at the correct face at the beginning. Once you shine the flashlight on a face, you'd be left with a single face to work with.
--------------------------------------------------------------------------------
Question:
Topic: Sequence solving
Question: Imagine a sequence that begins with the numbers 1, 11, 21, 1211, 111221. Each subsequent number is described by vocalizing the digits of the previous one. For example, the second number '11' is read as 'one one', which describes the first number, which is a single '1'. Similarly, the next number '21' is read as 'two ones'. What is the sixth number in the sequence?
Options:
1) 13112221
2) 1113213211
3) 312211
4) 2112132111
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 3)
Reasoning:
The sequence is known as the 'Look and Say' sequence. Each term describes the previous term. The fifth number '111221' is described as 'three ones, two twos, and one one', which gives us the sixth number '312211'.
Generated Answer:
Correct Answer: 2)
Reasoning:
The sequence is a Fibonacci sequence that starts with 1 and 11. The numbers progress as follows: 1, 11, 21, 1211, 111221. The next number '21' is read as 'two ones', which is not a valid vocalization of the number 21. Moving on, the sequence continues: 21, 111221, 111321, 211211, 1113211, 2112111, 1113211111. So, there is no sixth number in the sequence.
--------------------------------------------------------------------------------
Question:
Topic: Classic riddles
Question: A box contains a set of three different keys: one for the front door, one for the back door, and one for the safe. The keys are indistinguishable by touch. If you need to open the safe and you must pick one key without looking, what is the minimum number of key pulls required to guarantee that you have selected the key for the safe?
Options:
1) 1
2) 2
3) 3
4) 4
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 3)
Reasoning:
With the first pull, you have a 1 in 3 chance of pulling out the safe key. If you do not get the safe key on the first pull, put it back and pull again. The second pull then will also have a 1 in 3 chance of being the safe key. However, to guarantee that you get the safe key, you'd have to pull up to 3 keys to be sure you get it. The first two pulls could possibly be the front or back door keys, so by the time you pull the third key, it must be the one for the safe. So the minimum number of pulls to guarantee that you have the safe key is 3.
Generated Answer:
Correct Answer: 3)
Reasoning:
The minimum number of key pulls required to guarantee you have selected the key for the safe is 3. You can pull the first key, and then pull the second key on the same door. If you pull the second key on the first door, it won't fit in the second door, and you will definitely not be able to pull the third key on the same door. So, you'll need a total of three pulls to succeed.
--------------------------------------------------------------------------------
Question:
Topic: Optimization of actions and planning
Question: You are an events planner and have been tasked to organize three different events. The first event is a seminar that needs a room for 100 people. The second event is a workshop and requires a room for 25 people with additional space for art materials. The third event is a company meeting with 40 people that requires a conference table setup. You have access to four different rooms: Room A can hold up to 150 people, Room B can hold up to 50 people, Room C can hold up to 100 people, and Room D can hold 30 people with extra space for supplies. However, due to a scheduling conflict, Room A is only available in the morning. Which room should be assigned to which event for optimal use of space and considering the restrictions?
Options:
1) Seminar in Room A, Workshop in Room D, Meeting in Room B
2) Seminar in Room A, Workshop in Room B, Meeting in Room C
3) Seminar in Room C, Workshop in Room D, Meeting in Room A
4) Seminar in Room A, Workshop in Room D, Meeting in Room C
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 1)
Reasoning:
Assign Room A to the seminar since it's the only event with 100 people and needs the most space, and it can be held in the morning. Assign Room D to the workshop because it fits 25 people and has extra space for art materials. The company meeting with 40 people should go in Room C, which has space for 100 which is sufficient and allows Room D to be used where Room B would be too small.
Generated Answer:
Correct Answer: 3)
Reasoning:
Rooms A, B, and D can comfortably hold up to 150, 50, and 100 people, respectively. The problem is scheduling a conflict with the speaker and the workshop. Speaker cannot be present in the morning. Therefore, the speaker must take a break for lunch and return in the afternoon. The workshop can't have a speaker present in the morning as it requires the use of art materials. The workshop's speaker can take the break in the afternoon and attend to other tasks. The meeting cannot be attended by the speaker in the morning as it requires the use of conference supplies. Therefore, the meeting must be attended by someone who has some supplies on hand and can help with the cleanup afterward. The most optimal solution is to assign the seminar to Room A, the workshop to Room D, and the company meeting to Room B.
--------------------------------------------------------------------------------
Question:
Topic: Spatial reasoning
Question: Adam, Bella, Carlos, and Diana are standing at the corners of a large square field. Each person is instructed to walk halfway towards the person on their right and then stops. What shape do they form when all of them stop walking?
Options:
1) A smaller square
2) A rectangle
3) A larger square
4) An octagon
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 1)
Reasoning:
If each person walks halfway towards the person on their right, they will all stop at the midpoint of each side of the square field. Hence, they will form a smaller square which is rotated 45 degrees compared to the original one.
Generated Answer:
Correct Answer: 3)
Reasoning:
The only way for Adam, Bella, Carlos, and Diana to form the shape of a square walk is to walk in a straight line towards the person on their right, but they must make sure that they don't walk in a straight line to avoid getting stopped. If they start walking at the person's right corner and want to end up at the corner where the person started, how many of them will be standing at the corner where the walk ends?
Options:
1) 1
2) 2
3) 3
4) 4
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
--------------------------------------------------------------------------------
Question:
Topic: Lateral thinking
Question: A man is found hanging in a room with a puddle of water under his feet and nothing else in the room but a saw. The room has only one door and it is locked from the inside. The man left no message and there's no trace of a struggle. How did the man hang himself?
Options:
1) He climbed on a block of ice which later melted.
2) He jumped from a height.
3) He had an accomplice who escaped.
4) The man used magic.
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 1)
Reasoning:
The man stood on a block of ice and put the noose around his neck. As time went by, the ice melted, creating the puddle of water under his feet, and leaving him hanging.
Generated Answer:
Correct Answer: 3)
Reasoning:
The man didn't use any tools or force to hang himself. He was found hanging in the room with a saw under his feet. The only clue was the man leaving a puddle of water on him and the lack of any evidence of a struggle. It is possible that he climbed on a block of ice to hang himself, but the'melted' puddle doesn't necessarily indicate any struggle.
--------------------------------------------------------------------------------
Question:
Topic: Optimization of actions and planning
Question: A warehouse manager needs to arrange a schedule for 3 workers who will handle incoming shipments. There are 7 consecutive days, starting from Monday, and each worker can only work for 5 days in a row before requiring a 2-day break. The manager needs to ensure that for each day of the week, at least one worker is available to handle the shipments. The workers are equally skilled, and there are no other constraints. What is the optimal way for the manager to schedule the workers to meet the daily requirements?
Options:
1) A: Mon-Fri, B: Tue-Sat, C: Thu-Mon
2) A: Mon-Fri, B: Wed-Sun, C: Fri-Tue
3) A: Mon-Fri, B: Wed-Sun, C: Sat-Wed
4) A: Mon-Fri, B: Thu-Mon, C: Sat-Wed
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
To ensure that each day of the week has at least one worker, the manager can schedule the workers in overlapping shifts. Worker A can be scheduled from Monday to Friday, Worker B from Wednesday to Sunday, and Worker C from Saturday to Wednesday of the next week. This way, Monday and Tuesday have Worker A, Wednesday has Workers A and B, Thursday and Friday have Workers A and B, Saturday and Sunday have Workers B and C, and the cycle continues with at least one worker present every day.
Generated Answer:
Correct Answer: 5)
Reasoning:
The optimal schedule for the warehouse manager with the given constraints is to have the worker who can handle the most days of the week, say Worker 1, work on Monday, then Worker 2, who can handle the next 3 days (day 3), and finally Worker 3, who can handle the remaining 2 days (day 4). Since there are no other restrictions on the number of workers assigned to them, the manager can adjust the schedule as needed, potentially rotating someone or changing the pattern of work.
--------------------------------------------------------------------------------
Question:
Topic: Optimization of actions and planning
Question: You have to paint three houses, each one can be painted in one of three colors: red, green, or blue. The cost of painting each house a particular color is different and is given by a 3x3 cost matrix where the rows represent houses and the columns represent colors. Given the cost matrix [[17, 2, 17], [16, 16, 5], [14, 3, 19]], you have to paint each house in such a way that no two adjacent houses have the same color and the total cost of painting is minimized. What is the minimum cost?
Options:
1) 22
2) 10
3) 33
4) 18
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:

### LoRA/PEFT

In [ ]:
from transformers import pipeline
from trl import SFTConfig
from trl import SFTTrainer


base_model = "google/gemma-3-270m-it"
tokenizer = AutoTokenizer.from_pretrained(base_model)

lora_config = LoraConfig(
    r=16,                     # rank (capacity of adapter)
    lora_alpha=32,            # scaling factor
    lora_dropout=0.1,        # dropout inside LoRA layers
    bias="none",
    task_type="CAUSAL_LM"     # type of model
)

#Causal means predicting the next words from the previous ones
model = AutoModelForCausalLM.from_pretrained(
    base_model,
    torch_dtype="auto",
    device_map="auto",
    attn_implementation="eager"
)

model = get_peft_model(model, lora_config)
# pipe = pipeline("text-generation", model=model, tokenizer=tokenizer)

# # Load a random sample from the test dataset
# rand_idx = randint(0, len(hf_dataset["test"])-1)
# test_sample = hf_dataset["test"][rand_idx]

# # Convert as test example into a prompt with the model template
# prompt = pipe.tokenizer.apply_chat_template(test_sample["messages"][:1], tokenize=False, add_generation_prompt=True)
# outputs = pipe(prompt, max_new_tokens=256, disable_compile=True)

# # Extract the user query and original answer
# print(f"Question:\n{test_sample['messages'][0]['content']}\n")
# print(f"Original Answer:\n{test_sample['messages'][1]['content']}\n")
# print(f"Generated Answer (base model):\n{outputs[0]['generated_text'][len(prompt):].strip()}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.69M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.35k [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/536M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/173 [00:00<?, ?B/s]

In [ ]:
torch_dtype = model.dtype

sft_args = SFTConfig(
    output_dir="./lora_sft_model",
    num_train_epochs=10,                     # more epochs to compensate small data
    per_device_train_batch_size=2,           # small batch for better generalization
    gradient_accumulation_steps=4,           # simulate bigger batch
    learning_rate=1e-4,                      # smaller LR = smoother updates
    lr_scheduler_type="cosine",
    warmup_ratio=0.1,
    max_length=512,
    packing=False,
    optim="adamw_torch_fused",              # use fused adamw optimizer
    save_strategy="epoch",
    eval_strategy="epoch",
    fp16=True if torch_dtype == torch.float16 else False,   # use float16 precision
    bf16=True if torch_dtype == torch.bfloat16 else False,  # use bfloat16 precision
    report_to="none",                          # disable W&B
    push_to_hub=False,
    dataset_kwargs={
        "add_special_tokens": False, # Template with special tokens
        "append_concat_token": True, # Add EOS token as separator token between examples
    }
)

# Create Trainer object
trainer = SFTTrainer(
    model=model,
    args=sft_args,
    train_dataset=hf_dataset['train'],
    eval_dataset=hf_dataset['test'],
    processing_class=tokenizer,
)

Tokenizing train dataset:   0%|          | 0/307 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/307 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/77 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/77 [00:00<?, ? examples/s]

In [ ]:
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': 2, 'pad_token_id': 0}.

TrainOutput(global_step=390, training_loss=1.523431724157089, metrics={'train_runtime': 1090.0851, 'train_samples_per_second': 2.816, 'train_steps_per_second': 0.358, 'total_flos': 676769553157632.0, 'train_loss': 1.523431724157089, 'epoch': 10.0})

In [ ]:
reward_model = AutoModelForSequenceClassification.from_pretrained(
    "your_base_model", num_labels=1
)

In [ ]:
model = AutoModelForCausalLM.from_pretrained("./sft_model")
tokenizer = AutoTokenizer.from_pretrained("./sft_model")

grpo_config = GRPOConfig(
    learning_rate=1e-6,
    batch_size=8,
    kl_penalty="adaptive",
    sample_per_prompt=4,    # multiple responses per prompt
    reward_model_path="./reward_model"
)

trainer = GRPOTrainer(
    model=model,
    tokenizer=tokenizer,
    config=grpo_config,
    reward_model=reward_model,
    dataset=train_dataset
)

trainer.train()

In [ ]:
model_id = "./lora_sft_model/checkpoint-390"

# Load Model
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype="auto",
    device_map="auto",
    attn_implementation="eager"
)
tokenizer = AutoTokenizer.from_pretrained(model_id)

pipe = pipeline("text-generation", model=model, tokenizer=tokenizer)

def test(test_sample):
  # Convert as test example into a prompt with the Gemma template
  prompt = pipe.tokenizer.apply_chat_template(test_sample["messages"][:1], tokenize=False, add_generation_prompt=True)
  outputs = pipe(prompt, max_new_tokens=256, disable_compile=True)

  # Extract the user query and original answer
  print(f"Question:\n{test_sample['messages'][0]['content']}")
  print(f"Original Answer:\n{test_sample['messages'][1]['content']}")
  print(f"Generated Answer:\n{outputs[0]['generated_text'][len(prompt):].strip()}")
  print("-"*80)

# Test with an unseen dataset
for item in hf_dataset['test']:
  test(item)

Device set to use cuda:0

Question:
Topic: Sequence solving
Question: You are given a sequence of numbers where each number represents an action. The actions are defined as follows: 1-Add 3, 2-Subtract 2, 3-Multiply by 5, and 4-Divide by 2. Starting with the number 10, follow the sequence of actions 2, 1, 3, 2, 4, 1. What is the result after performing all these actions in the given order?
Options:
1) 27.5
2) 29.5
3) 32.5
4) 34.5
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
Starting with the number 10, follow each action step by step:
- Step 1 (2): 10 - 2 = 8
- Step 2 (1): 8 + 3 = 11
- Step 3 (3): 11 * 5 = 55
- Step 4 (2): 55 - 2 = 53
- Step 5 (4): 53 / 2 = 26.5
- Step 6 (1): 26.5 + 3 = 29.5
Hence, the result after following the actions in the given order is 29.5.
Generated Answer:
Correct Answer: 1)
Reasoning:
Starting with 10, we add 2 to the first number, which yields 12. Subtracting 2 from the second number, we get 10. Multiply this by 5, which yields 50. Divide the result by 2, which yields 25. Add the result to the third number, which yields 25. Subtracting 2 from the fourth number, we get 21. Multiply the result by 5, which yields 50. Divide the result by 2, which yields 25. Subtract 2 from the fifth number, we get 21. Multiply the result by 5, which yields 100. Divide the result by 2, which yields 50. Add the result to the sixth number, which yields 100. Subtract 2 from the seventh number, we get 98. Multiply the result by 5, which yields 495. Divide the result by 2, which yields 247. Subtract 2 from the eighth number, we get 245. Multiply the result by 5, which yields 525. Divide the
--------------------------------------------------------------------------------
Question:
Topic: Sequence solving
Question: Alice has created a sequence where each number is generated by adding the square of the number's position in the sequence (where the first position is 1, the second position is 2, and so on) to the previous number. If the sequence starts with 1, what is the 6th number in the sequence?
Options:
1) 81
2) 66
3) 77
4) 91
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 4)
Reasoning:
The sequence starts with 1. To generate subsequent numbers, we add the square of the position number to the previous value: 2nd number: 1 + 2^2 = 5 3rd number: 5 + 3^2 = 14 4th number: 14 + 4^2 = 30 5th number: 30 + 5^2 = 55 6th number: 55 + 6^2 = 91 Thus, the 6th number in the sequence is 91.
Generated Answer:
Correct Answer: 2)
Reasoning:
The sequence is given as (1 + 2^2 + 3^2 + 4^2 + 5^2) + (2^3 + 3^3 + 4^3 + 5^3) = (1 + 4 + 9 + 16 + 25) + (2^3 + 3^3 + 4^3 + 5^3) = (1 + 4 + 9 + 16 + 25) + (2^3 + 3^3 + 4^3 + 5^3) = 54 + 2^3 + 3^3 + 4^3 + 5^3
--------------------------------------------------------------------------------
Question:
Topic: Logical traps
Question: Alice, Bob, and Charlie are participants in a game show. The host shows them five hats: three red and two blue. Each participant is blindfolded and has one hat placed on their head; the remaining hats are hidden. They can't see their own hat, but they can see the hats of the other two participants. The first to correctly announce the color of their own hat wins a prize. Alice sees that Bob and Charlie have red hats. Bob sees that Alice and Charlie have red hats. Charlie sees that Alice and Bob have red hats. They all deduce logically and do not guess. Alice says she doesn't know the color of her hat. Bob also says he doesn't know the color of his hat. Charlie then announces the color of his hat. What color is Charlie's hat, and what is the logical explanation?
Options:
1) Red
2) Blue
3) The color cannot be determined
4) Not enough information
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
Charlie's hat is red. Since Alice sees two red hats, if her hat were blue, Bob would see one red and one blue hat. In that case, knowing there are only two blue hats, Bob would deduce that his hat must be red. However, Bob didn't know the color of his hat, which means Alice's hat must be red. Bob sees two red hats as well, and if his hat were blue, following the same logic as before, Charlie would have answered without waiting for Bob to speak. Since Charlie also didn't know until Bob spoke, it means all three participants are wearing red hats.
Generated Answer:
Correct Answer: 2)
Reasoning:
Alice's hat is red. Charlie's hat is blue. Bob's hat is red. Charlie's hat is red. Alice's hat is blue. Since Bob and Charlie are red, and Alice cannot know her hat color, then Charlie must have a blue hat.
--------------------------------------------------------------------------------
Question:
Topic: Sequence solving
Question: You are given a sequence of numbers where each number is the product of the previous two numbers minus the sum of the previous two numbers plus 2: 4, 5, 14, 58, ... What is the next number in the sequence?
Options:
1) 208
2) 53
3) 77
4) 82
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 5)
Reasoning:
The next number is calculated as follows: Take the last two numbers from the given sequence, multiply them and then subtract their sum before adding 2. If the last two numbers are 5 and 14, their product is 70. We then subtract the sum of 5 and 14, which is 19, from 70 to get 51. Finally, we add 2, resulting in the next number being 53. Using this method, following the sequence starting with 4 and 5, we get: (4*5 - (4+5) + 2) = 14, (5*14 - (5+14) + 2) = 58, (14*58 - (14+58) + 2) = 53. Therefore, the next number is 53.
Generated Answer:
Correct Answer: 3)
Reasoning:
The sequence is given as 4, 5, 14, 58,... This is a sequence of the form: a_n = a_1 * a_2 - a_1 + a_2 - a_1 + a_2 - a_1 + a_2 - a_1 - a_1 + a_2 - a_1 - a_1 + a_2 - a_1 - a_1 + a_2 - a_1 + a_2 - a_1 - a_1.
The next number is 58 - (a_1 + a_2) = 58 - a_1 - a_2.
The next number is 58 - (a_1 + a_2) + 2 = 58 - a_1 - a_2 + 2
The next number is 58 - (a_1 + a_2) - a_1 - a_2 + 2 = 58 - a_1 - a_2 - a_1 - a_2 + 2
The next number is 58 - (
--------------------------------------------------------------------------------
Question:
Topic: Operation of mechanisms
Question: In a certain mechanical workshop, there are three machines that can only operate one at a time due to limited electrical capacity. Machine A takes 3 hours to complete its job. Machine B takes 4 hours, and Machine C takes 6 hours. They all need to complete one job each. The workshop operates an 8-hour workday. If only one machine can operate at any given time and no machine can be stopped mid-operation, what is the maximum number of full days needed to complete all three jobs?
Options:
1) 1 day
2) 2 days
3) 3 days
4) 4 days
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
Machine A takes 3 hours, B takes 4 hours, and C takes 6 hours. In an 8-hour workday, you can run A and B on the first day (3+4 = 7 hours). On the second day, you can run machine C for 6 hours. Thus, the maximum number of full days needed to complete all jobs without breaking any machine's operation midway is 2 full days.
Generated Answer:
Correct Answer: 2)
Reasoning:
The maximum number of full days required to complete all three jobs is 8. Machine A takes 3 hours, Machine B takes 4 hours, and Machine C takes 6 hours. Machine B works at a rate of 4 hours per day, Machine C works at a rate of 6 hours per day, and Machine A works at a rate of 3 hours per day. Therefore, the total work done is 3 + 4 + 6 = 13 hours. However, the workshop operates an 8-hour workday, so it takes 13 hours to complete all three jobs. Machine A takes 3 hours to complete one job, Machine B takes 4 hours, and Machine C takes 6 hours. Since the total is 13 hours, Machine A will finish the job before Machine B, and Machine C will finish the job after Machine A.
--------------------------------------------------------------------------------
Question:
Topic: Spatial reasoning
Question: You are in a room with 4 doors, each door is painted with a different color; red, blue, green, and yellow. Each door leads to a room of the same color. Once you enter a colored room, there is another door that leads back to the original room which is not necessarily the same color as the one you entered. The red room leads back through the green door, the green room leads back through the red door, the blue room leads back through the yellow door. Which door leads back to the original room when you exit from the yellow room?
Options:
1) Red Door
2) Green Door
3) Blue Door
4) Yellow Door
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 3)
Reasoning:
Since the green room leads back through the red door, the red room leads back through the green door, and the blue room leads back through the yellow door, the only option left is that the yellow room leads back through the blue door.
Generated Answer:
Correct Answer: 3)
Reasoning:
You enter the yellow room. The red door leads you back to the original room, and the green door leads you back to the original room. The blue door leads you back to the original room, and the green door leads you back to the original room. The red door leads you back to the original room, and the yellow door leads you back to the original room.
--------------------------------------------------------------------------------
Question:
Topic: Classic riddles
Question: A king has 100 bottles of wine, and one of them is poisoned. The poison is such that if ingested, the effects are visible only after 24 hours. The king needs to find the poisoned bottle by tomorrow so he can execute the culprit at a banquet. He has 10 prisoners at his disposal to act as tasters. How can the king use the prisoners to identify the poisoned bottle by the next day?
Options:
1) Assign each prisoner to drink from 10 different bottles
2) Use a binary system to minimize the number of tasters while ensuring one tasting round
3) Let each prisoner taste randomly until one of them shows the effects of poison
4) Divide the bottles into 10 groups of 10 and have each prisoner taste an entire group
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
The king can assign each bottle a number from 1 to 100 and then convert those numbers into binary. Each prisoner will be assigned a bit position, from the first (1) to the tenth (1024). For every bottle, if the number has a '1' in a prisoner's bit position, that prisoner drinks from the bottle. For example, the bottle number 3 is 0011 in binary; therefore, prisoners number 1 and 2 will drink from this bottle. If bottle number 58, which is 111010 in binary, is poisoned, prisoners 1, 2, 4, and 6 will die, and from the binary pattern, the king will know that bottle 58 is the poisoned one. This will require the least amount of prisoners and testing to find out the poisoned bottle in one go.
Generated Answer:
Correct Answer: 2)
Reasoning:
The king is to deduce the poison by examining the bottles that are left empty after 24 hours. He finds the poison in one bottle, and the next bottle will have the poison. After 24 hours, the poison is found in another bottle, and the next one will have the poison. The king then has 10 prisoners, each tasting from 1 to 10 bottles. The king then starts tasting from the first bottle, and the poison is found in the next bottle. After the king has tasted 9 bottles, he can deduce the poison by tasting from the 10th bottle, and the poison is found in the next bottle, and the king can deduce the poison by tasting from the 10th bottle, and the poison is found in the next bottle.
--------------------------------------------------------------------------------
Question:
Topic: Optimization of actions and planning
Question: You have 4 tasks to complete with different priorities and durations. Task A has a duration of 4 hours with a high priority. Task B takes 1 hour with a medium priority. Task C occupies you for 3 hours with a low priority. Task D is 2 hours long with a high priority. Your challenge is to minimize the total time spent on tasks by efficiently ordering their completion based on the principle that high priority tasks can't be postponed unless a higher priority task is occupying the slot. If a task is started it must be finished before another is taken up. What is the sequence of tasks that ensures the shortest time to complete all the tasks, taking into account the given constraints?
Options:
1) A-B-C-D
2) A-D-B-C
3) D-B-A-C
4) B-A-D-C
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 3)
Reasoning:
According to the problem constraints, high priority tasks should be done first unless they are longer and a shorter medium priority task can be done in meantime. Therefore, start with Task D (high priority, 2 hours), then do Task B (medium priority, 1 hour) while waiting to begin Task A (since it's longer), and finish with Task A (high priority, 4 hours), ending with Task C (low priority, 3 hours). The sequence is D-B-A-C.
Generated Answer:
Correct Answer: 2)
Reasoning:
The sequence of tasks is A-B-C-D, which takes 4 hours. The minimum time to complete all tasks is 4 hours. Therefore, the sequence must be B-C-D-A. This means the duration of each task must be at least 3 hours, and that only one task can be completed before another is taken up. Since we know that Task B takes 1 hour, and we're aiming for 3 hours to complete the first task, the remaining 2 hours must be used for B-C-D-A. Thus, the sequence is B-C-D-A.
--------------------------------------------------------------------------------
Question:
Topic: Spatial reasoning
Question: You are in charge of arranging different colored cubes in a 3x3x3 cube grid. The grid must be filled so that each 1x1x1 cube touches exactly one other cube of the same color along one of its faces. You have equal numbers of red, green, and blue cubes. How many ways are there to arrange the cubes in the grid following these rules?
Options:
1) 6 ways
2) 24 ways
3) 32 ways
4) 48 ways
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 5)
Reasoning:
Each layer of the 3x3x3 cube can be considered as a separate problem. Since each cube must touch exactly one cube of the same color, each color in a layer must form an L shape. There are two possible L shapes for each color (mirrored). This can be arranged in each layer in 2 ways for each color and there are 3 layers. Since the first layer has 2^3 options, and the colors in the subsequent layers are dependent on the layer below (to prevent vertical matching), there are 3 layers giving us 2^3 * 2^2 * 2^1 = 32 unique ways to arrange the cubes.
Generated Answer:
Correct Answer: 2)
Reasoning:
Let's consider the cubes in the 3x3x3 grid. Each cube has a unique color. Since there are 4 different colors of cubes, and we are given that the total number of cubes is equal, the number of cubes that can be arranged in the grid is equal to the number of colors. Thus, there are 4 ways to arrange the 4 colors. Each of the 4 colors will have the same number of cubes, so the number of ways to arrange the 4 colors is the number of ways to arrange the 4 colors, which is 4.
--------------------------------------------------------------------------------

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Question:
Topic: Operation of mechanisms
Question: In a factory, there are three machines A, B, and C. Machine A can produce 30 widgets per hour. Machine B can produce 20 widgets more per hour than Machine A, but it's only 80% as reliable (meaning it's operational 80% of the time B operates). Machine C is two times less productive than Machine A, but it never breaks down. If all machines start working simultaneously, after 4 hours of operation, due to a power outage, only one of the machines can be operated for an additional 2 hours. Which machine should be operated after the power outage to maximize the number of widgets produced at the end of the 6-hour period, assuming that machine B, if selected, will not face any reliability issues during those additional hours?
Options:
1) Machine A
2) Machine B
3) Machine C
4) None of the machines
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
Machine A produces 30 widgets per hour. Machine B produces 50 widgets per hour (30 + 20) and is 80% reliable, so on average, it produces 40 widgets per hour (50 * 0.8). Machine C produces 15 widgets per hour. In 4 hours, A would produce 120 widgets, B would produce 160 widgets (assuming no downtime), and C would produce 60 widgets. For the next 2 hours, A would produce 60 more widgets, B would produce 100 more widgets, and C would produce 30 more widgets. Therefore, operating machine B for the additional 2 hours results in the highest number of widgets, bringing the total to 260 widgets (160 + 100).
Generated Answer:
Correct Answer: 6)
Reasoning:
Machine A starts with 30 widgets per hour and is only 80% reliable. Machine B, with 20 widgets per hour, is 80% more reliable than Machine A, so it's 80% of the time successful. Machine C is two times less productive than Machine A, so it has 80% of the time unsuccessful. Machine C has to operate for 4 hours, and the total time is 6 hours. After the power outage, Machine B will be operational for 4 hours, and Machine C will be operational for 6 hours. Thus, after the power outage, Machine A will be operational for 6 hours, and Machine C will be operational for 6 hours. Since both machines will be operational, the total number of widgets produced after the power outage is 6 + 6 = 12 widgets, and the number of widgets produced in total is 12 * 30 = 360 widgets. Therefore, Machine A should be operated first, as it produces 360 widgets in 6 hours, which is more than the 360 widgets produced by Machine B, and the number of widgets produced
--------------------------------------------------------------------------------
Question:
Topic: Lateral thinking
Question: There is one word in the English language that is always pronounced incorrectly. What is it?
Options:
1) Wednesday
2) Incorrectly
3) Queue
4) Colonel
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
The solution to this lateral thinking puzzle is not a matter of knowledge about the language, but understanding that the question itself is a play on words. The word 'incorrectly' itself is always pronounced 'incorrectly', as that is its correct pronunciation—it is a trick question that plays on the literal meaning of the statement itself.
Generated Answer:
Correct Answer: 2)
Reasoning:
The correct answer is 2) The word is 'incorrectly' because the word is always pronounced incorrectly.
--------------------------------------------------------------------------------
Question:
Topic: Sequence solving
Question: Imagine a sequence where each term is the result of the multiplication of the sum of the digits of the previous term. The sequence starts with 289. What is the 4th term in the sequence?
Options:
1) 100
2) 19
3) 361
4) 1
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 5)
Reasoning:
The sequence starts with 289. The sum of digits of 289 is 2 + 8 + 9 = 19. The second term is therefore the result of 19 multiplied by itself, which is 361. Sum of digits of 361 is 3 + 6 + 1 = 10. The third term is 10 multiplied by itself, which is 100. Now, the sum of digits of 100 is 1 + 0 + 0 = 1. So, the fourth term is 1 multiplied by itself, which is 1.
Generated Answer:
Correct Answer: 3)
Reasoning:
The sequence has 4 terms, and the next term is 361. Since the sum of the digits of the previous term is 362, the next term is 361 * 3 = 1088. Since the sum of the digits is 1088, we can write the 4th term as 361 * 1088 = 361072.
--------------------------------------------------------------------------------
Question:
Topic: Sequence solving
Question: In a certain number sequence, each number after the first follows a specific but simple rule based on its position and the preceding number. The sequence starts with 1 and the first six numbers are: 1, 2, 4, 7, 11, 16. What is the seventh number in the sequence?
Options:
1) 19
2) 20
3) 21
4) 22
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 4)
Reasoning:
The sequence follows a rule where each number is the sum of the preceding number and the position of that preceding number in the sequence. So the second number is 1 (the first number) + 1 (its position) = 2, the third number is 2 (the second number) + 2 (its position) = 4, and so on. Following this pattern, the seventh number is the sixth number (16) plus its position (6), which equals 22.
Generated Answer:
Correct Answer: 2)
Reasoning:
The sequence is the sequence of numbers starting from 1 and following the pattern 1, 2, 4, 7, 11, 16. The first number is 1. The sequence is the sequence of consecutive multiples of 2, starting from 1 and being continued. The second number is 2. The sequence is the sequence of consecutive multiples of 4, starting from 2 and being continued. The third number is 4. The sequence is the sequence of consecutive multiples of 7, starting from 4 and being continued. The fourth number is 7. The sequence is the sequence of consecutive multiples of 11, starting from 7 and being continued. The fifth number is 11. The sequence is the sequence of consecutive multiples of 16, starting from 11 and being continued. The sixth number is 16.
--------------------------------------------------------------------------------
Question:
Topic: Spatial reasoning
Question: Imagine you're looking at a cube that has 6 faces, each face painted with a different color: red, blue, yellow, green, orange, and purple. The cube is then placed inside a completely dark room. You have a flashlight that you can shine on only one face of the cube at a time to reveal its color. What is the minimum number of faces you need to illuminate to guarantee you can determine the color of every face of the cube?
Options:
1) 2
2) 3
3) 4
4) 5
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
The minimum number of faces you need to illuminate to determine the color of every face of the cube is 3, provided you choose the right faces. If you illuminate one face, you see that color, and you automatically know the color of the opposite face cannot be any of the remaining colors you find. Then, illuminate an adjacent face to the one you already lit up (this gives you two adjacent sides). Now you have three unknown colors and two more faces to check. By illuminating another face adjacent to the first two (but not opposite the second illuminated face), you will see the third color and know which two colors are left for the remaining faces. Since the opposite faces of a cube are always the remaining two colors, you don't need to illuminate them, you will already know their colors.
Generated Answer:
Correct Answer: 2)
Reasoning:
The minimum number of faces you need to illuminate is 5. Since you can illuminate only one face at a time, you need to illuminate all 6 faces to determine the color of each face.
--------------------------------------------------------------------------------
Question:
Topic: Sequence solving
Question: Imagine a sequence that begins with the numbers 1, 11, 21, 1211, 111221. Each subsequent number is described by vocalizing the digits of the previous one. For example, the second number '11' is read as 'one one', which describes the first number, which is a single '1'. Similarly, the next number '21' is read as 'two ones'. What is the sixth number in the sequence?
Options:
1) 13112221
2) 1113213211
3) 312211
4) 2112132111
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 3)
Reasoning:
The sequence is known as the 'Look and Say' sequence. Each term describes the previous term. The fifth number '111221' is described as 'three ones, two twos, and one one', which gives us the sixth number '312211'.
Generated Answer:
Correct Answer: 1)
Reasoning:
The sequence consists of the numbers 1, 11, 21, 1211, 111221. The sequence starts with 1. The sequence is calculated as:
11 + 21 = 32
32 + 1211 = 1233
1233 + 111221 = 113554
The next number is 111321. The sequence is 113554. The sixth number is 111321.
--------------------------------------------------------------------------------
Question:
Topic: Classic riddles
Question: A box contains a set of three different keys: one for the front door, one for the back door, and one for the safe. The keys are indistinguishable by touch. If you need to open the safe and you must pick one key without looking, what is the minimum number of key pulls required to guarantee that you have selected the key for the safe?
Options:
1) 1
2) 2
3) 3
4) 4
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 3)
Reasoning:
With the first pull, you have a 1 in 3 chance of pulling out the safe key. If you do not get the safe key on the first pull, put it back and pull again. The second pull then will also have a 1 in 3 chance of being the safe key. However, to guarantee that you get the safe key, you'd have to pull up to 3 keys to be sure you get it. The first two pulls could possibly be the front or back door keys, so by the time you pull the third key, it must be the one for the safe. So the minimum number of pulls to guarantee that you have the safe key is 3.
Generated Answer:
Correct Answer: 3)
Reasoning:
To guarantee the safe opens, you must pick one key without looking, and then pick the key that unlocks the safe. There are three possible ways to do this:
1) Pick the key on the back door.
2) Pick the key on the front door.
3) Pick the key on the safe door.
Each of these has the minimum number of pulls required to open the safe. Since there are 3 possible ways to pick the key, we need to consider how much time we need to take.
With 1 pull, the safe can be unlocked in 1 pull. With 2 pulls, the safe will open in 2 pulls. With 3 pulls, the safe will be unlocked in 3 pulls.
--------------------------------------------------------------------------------
Question:
Topic: Optimization of actions and planning
Question: You are an events planner and have been tasked to organize three different events. The first event is a seminar that needs a room for 100 people. The second event is a workshop and requires a room for 25 people with additional space for art materials. The third event is a company meeting with 40 people that requires a conference table setup. You have access to four different rooms: Room A can hold up to 150 people, Room B can hold up to 50 people, Room C can hold up to 100 people, and Room D can hold 30 people with extra space for supplies. However, due to a scheduling conflict, Room A is only available in the morning. Which room should be assigned to which event for optimal use of space and considering the restrictions?
Options:
1) Seminar in Room A, Workshop in Room D, Meeting in Room B
2) Seminar in Room A, Workshop in Room B, Meeting in Room C
3) Seminar in Room C, Workshop in Room D, Meeting in Room A
4) Seminar in Room A, Workshop in Room D, Meeting in Room C
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 1)
Reasoning:
Assign Room A to the seminar since it's the only event with 100 people and needs the most space, and it can be held in the morning. Assign Room D to the workshop because it fits 25 people and has extra space for art materials. The company meeting with 40 people should go in Room C, which has space for 100 which is sufficient and allows Room D to be used where Room B would be too small.
Generated Answer:
Correct Answer: 2)
Reasoning:
The second event requires a conference table, which has 25 people. If the conference table is used, we have 25 people for the event, and room D can hold 30 people. So, room D would be the most suitable room for the event, assuming room D is available. Room A is only available in the morning. Room B is available, and room C is available. Room D is available, but it's not the most suitable room. Therefore, Room D is the best choice.
--------------------------------------------------------------------------------
Question:
Topic: Spatial reasoning
Question: Adam, Bella, Carlos, and Diana are standing at the corners of a large square field. Each person is instructed to walk halfway towards the person on their right and then stops. What shape do they form when all of them stop walking?
Options:
1) A smaller square
2) A rectangle
3) A larger square
4) An octagon
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 1)
Reasoning:
If each person walks halfway towards the person on their right, they will all stop at the midpoint of each side of the square field. Hence, they will form a smaller square which is rotated 45 degrees compared to the original one.
Generated Answer:
Correct Answer: 2)
Reasoning:
The squares form a rectangle with the center at the center of the square and the right side of the square being at the same distance from the center. They are also connected by the side of the square, and the side of the square is the distance from the center of the square to the left side.
--------------------------------------------------------------------------------
Question:
Topic: Lateral thinking
Question: A man is found hanging in a room with a puddle of water under his feet and nothing else in the room but a saw. The room has only one door and it is locked from the inside. The man left no message and there's no trace of a struggle. How did the man hang himself?
Options:
1) He climbed on a block of ice which later melted.
2) He jumped from a height.
3) He had an accomplice who escaped.
4) The man used magic.
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 1)
Reasoning:
The man stood on a block of ice and put the noose around his neck. As time went by, the ice melted, creating the puddle of water under his feet, and leaving him hanging.
Generated Answer:
Correct Answer: 3)
Reasoning:
The man climbed on a block of ice which melted, and then he jumped, which was an escape route.
--------------------------------------------------------------------------------
Question:
Topic: Optimization of actions and planning
Question: A warehouse manager needs to arrange a schedule for 3 workers who will handle incoming shipments. There are 7 consecutive days, starting from Monday, and each worker can only work for 5 days in a row before requiring a 2-day break. The manager needs to ensure that for each day of the week, at least one worker is available to handle the shipments. The workers are equally skilled, and there are no other constraints. What is the optimal way for the manager to schedule the workers to meet the daily requirements?
Options:
1) A: Mon-Fri, B: Tue-Sat, C: Thu-Mon
2) A: Mon-Fri, B: Wed-Sun, C: Fri-Tue
3) A: Mon-Fri, B: Wed-Sun, C: Sat-Wed
4) A: Mon-Fri, B: Thu-Mon, C: Sat-Wed
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
To ensure that each day of the week has at least one worker, the manager can schedule the workers in overlapping shifts. Worker A can be scheduled from Monday to Friday, Worker B from Wednesday to Sunday, and Worker C from Saturday to Wednesday of the next week. This way, Monday and Tuesday have Worker A, Wednesday has Workers A and B, Thursday and Friday have Workers A and B, Saturday and Sunday have Workers B and C, and the cycle continues with at least one worker present every day.
Generated Answer:
Correct Answer: 2)
Reasoning:
To ensure that the manager has enough workers available for each day, the manager needs to make sure that at least one worker is available for each of the 7 consecutive days. The minimum number of workers for each day is 4, so the manager can work 4 days in a row with at least one worker available for each day. The 7 consecutive days are Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, and Sunday. The manager can assign the workers to the 4 days in a row to fulfill the requirements of the 7 days.
--------------------------------------------------------------------------------
Question:
Topic: Optimization of actions and planning
Question: You have to paint three houses, each one can be painted in one of three colors: red, green, or blue. The cost of painting each house a particular color is different and is given by a 3x3 cost matrix where the rows represent houses and the columns represent colors. Given the cost matrix [[17, 2, 17], [16, 16, 5], [14, 3, 19]], you have to paint each house in such a way that no two adjacent houses have the same color and the total cost of painting is minimized. What is the minimum cost?
Options:
1) 22
2) 10
3) 33
4) 18
5) Another answer
Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks.
Original Answer:
Correct Answer: 2)
Reasoning:
Examine each color choice for the first house and then choose the color for the second house that is not the same as the first and has the minimum cost. Then, pick the color for the third house that is not the same as the second and has the minimum remaining cost. Calculations for the first house color choices: Red: 17 + min(Green or Blue for the second house) = 17 + min(16, 5) = 17 + 5 = 22; Green: 2 + min(Red or Blue for the second house) = 2 + min(16, 5) = 2 + 5 = 7; Blue: 17 + min(Red or Green for the second house) = 17 + min(16, 16) = 17 + 16 = 33. Now, we choose the second house color based on the first house being green (cheapest option), hence: Red: 7 + min(Green or Blue for the third house) = 7 + min(3, 19) = 7 + 3 = 10; Blue: 7 + min(Red or Green for the third house) = 7 + min(14, 3) = 7 + 3 = 10. Since both options give the same total cost, we can choose the third house to be red or blue. So, the minimum cost is 10.
Generated Answer:
Correct Answer: 2)
Reasoning:

KeyboardInterrupt:

### RLHF

In [ ]:
class Config:
    # model & tokenizer
    base_model: str = "google/gemma-3-270m-it"  # example — replace with a model you have access to
    login_token: str = "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"
    sft_output_dir: str = "./sft"
    reward_output_dir: str = "./reward"
    grpo_output_dir: str = "./grpo"

    # datasets (examples)
    sft_dataset: str = "./train.csv"            # HF dataset id or local path with prompt-response pairs for SFT
    reward_dataset: str = "./train.csv"         # HF dataset id or local path containing pairwise preferences for RM
    # reward_dataset must contain fields: "prompt", "response_a", "response_b", "label" (1 if a > b else 0)

    # training hyperparams (SFT)
    sft_epochs: int = 5
    sft_batch_size: int = 4
    sft_lr: float = 5e-5

    # GRPO hyperparams
    grpo_learning_rate: float = 2e-5
    grpo_batch_size: int = 2
    grpo_sample_per_prompt: int = 4
    grpo_epochs: int = 5

    # LoRA (optional)
    use_lora: bool = True
    lora_r: int = 8         #rank to be used
    lora_alpha: int = 16
    lora_dropout: float = 0.1

cfg=Config()

In [ ]:
def create_conversation(sample):
  return {
    "messages": [
        {
            "role": "user",
            "content": (
                f"Topic: {sample['topic']}\n"
                f"Question: {sample['problem_statement']}\n"
                f"Options:\n"
                f"1) {sample['answer_option_1']}\n"
                f"2) {sample['answer_option_2']}\n"
                f"3) {sample['answer_option_3']}\n"
                f"4) {sample['answer_option_4']}\n"
                f"5) {sample['answer_option_5']}\n"
                "Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks."
            )
        },
        {
            "role": "assistant",
            "content": (
                f"Correct Answer: {sample['correct_option_number']})\n"
                f"Reasoning:\n{sample['solution']}"
            )
        }
    ]
  }

def init_sft_dataset():
  df=pd.read_csv(cfg.sft_dataset)
  hf_dataset = Dataset.from_pandas(df)
  # Now you can map your function safely
  hf_dataset = hf_dataset.map(create_conversation, remove_columns=hf_dataset.column_names, batched=False)
  # Split dataset into 80% training samples and 20% test samples
  hf_dataset = hf_dataset.train_test_split(test_size=0.2, shuffle=False)

  return hf_dataset

In [ ]:
def train_sft():
    """
    Train SFT model from (prompt, response) pairs.
    Expected dataset format: each example should have 'prompt' and 'response' fields.
    Saves SFT model to cfg.sft_output_dir
    """
    login(token=cfg.login_token)

    tokenizer = AutoTokenizer.from_pretrained(cfg.base_model)
    model = AutoModelForCausalLM.from_pretrained(
        cfg.base_model,
        torch_dtype="auto",
        device_map="auto",
        attn_implementation="eager"
        )

    if cfg.use_lora:
        print("Applying LoRA to the model (PEFT)...")
        # model = prepare_model_for_kbit_training(model)
        lora_config = LoraConfig(
            r=cfg.lora_r,
            lora_alpha=cfg.lora_alpha,
            target_modules=["q_proj","v_proj","k_proj","v_proj"],
            lora_dropout=cfg.lora_dropout,
            bias="none"
        )
        model = get_peft_model(model, lora_config)

    # torch_dtype = model.dtype

    # Load dataset
    if cfg.sft_dataset:
       sft_dataset=init_sft_dataset()
    else:
        raise ValueError("Please set cfg.sft_dataset to a dataset with 'prompt' and 'response' fields.")

    torch_dtype = model.dtype

    print("Initializing SFTTrainer ...")
    training_args = SFTConfig(
        output_dir=cfg.sft_output_dir,
        num_train_epochs=cfg.sft_epochs,
        per_device_train_batch_size=cfg.sft_batch_size,
        learning_rate=cfg.sft_lr,
        max_length=512,                         # max sequence length for model and packing of the dataset
        packing=False,                          # Groups multiple samples in the dataset into a single sequence
        gradient_checkpointing=False,           # Caching is incompatible with gradient checkpointing
        optim="adamw_torch_fused",              # use fused adamw optimizer
        logging_steps=50,                       # log every 50 steps
        save_strategy="epoch",                  # save checkpoint every epoch
        eval_strategy="epoch",                  # evaluate checkpoint every epoch
        fp16=True if torch_dtype == torch.float16 else False,   # use float16 precision
        bf16=True if torch_dtype == torch.bfloat16 else False,  # use bfloat16 precision
        lr_scheduler_type="linear",           # use constant learning rate scheduler
        push_to_hub=False,                      # push model to hub
        report_to="none",
        dataset_kwargs={
            "add_special_tokens": False, # Template with special tokens
            "append_concat_token": True, # Add EOS token as separator token between examples
        }
    )

    trainer = SFTTrainer(
      model=model,
      args=training_args,
      train_dataset=sft_dataset['train'],
      eval_dataset=sft_dataset['test'],
      # dataset_text_field="none", # important when using "messages"
      # formatting_func="none",
      processing_class=tokenizer,
    )

    print("Starting SFT training...")
    trainer.train()
    print(f"SFT finished. Model saved to {cfg.sft_output_dir}")

In [ ]:
def create_prompt(sample):
  return {
    "prompt": [
        {
            "role": "user",
            "content": (
                f"Topic: {sample['topic']}\n"
                f"Question: {sample['problem_statement']}\n"
                f"Options:\n"
                f"1) {sample['answer_option_1']}\n"
                f"2) {sample['answer_option_2']}\n"
                f"3) {sample['answer_option_3']}\n"
                f"4) {sample['answer_option_4']}\n"
                f"5) {sample['answer_option_5']}\n"
                "Which one is the correct answer? Explain with proper reasoning while dividing your reasoning into subtasks."
            )
        }
    ],
    "truth": [
        {
            "role": "assistant",
            "content": (
                f"Correct Answer: {sample['correct_option_number']})\n"
                f"Reasoning:\n{sample['solution']}"
            )
        }
    ]
  }

def init_reward_dataset():
  df=pd.read_csv(cfg.reward_dataset)
  hf_dataset = Dataset.from_pandas(df)
  # Now you can map your function safely
  hf_dataset = hf_dataset.map(create_prompt, remove_columns=hf_dataset.column_names, batched=False)
  # Split dataset into 80% training samples and 20% test samples
  hf_dataset = hf_dataset.train_test_split(test_size=0.2, shuffle=False)

  return hf_dataset

In [ ]:
embedder = SentenceTransformer('all-MiniLM-L6-v2')
# reference_embeddings = embedder.encode(reference_reasoning_list, convert_to_tensor=True)

def parse_output(text):
    """
    Extracts the selected option (1–5) and reasoning section from the model's output.
    Expected format example:
        Correct Answer: 3)
        Reasoning: The capital of France is Paris...
    """
    # Match the answer like "Correct Answer: 3)"
    ans_match = re.search(r'(?:Correct\s*Answer)\s*[:\-]?\s*([1-5])\)', text)
    option = ans_match.group(1) if ans_match else None

    return option


def reasoning_similarity(model_reasoning, reference_reasoning):
    # Load a pretrained embedding model
    embeddings = embedder.encode([model_reasoning, reference_reasoning], convert_to_tensor=True)
    similarity = util.cos_sim(embeddings[0], embeddings[1]).item()      # embeddings[0] = vector for model reasoning
    return similarity                                                   # embeddings[1] = vector for reference reasoning


def simple_reward_fn(truth,completions, **kwargs):
    """
    Reward scheme:
    +4 -> correct option + correct reasoning
    +2 -> correct option
    -1 -> wrong or malformed
    """
    rewards=[]
    reward=None
    for output, gt in zip(completions, truth):
      if isinstance(output, list):
            output = " ".join([msg.get("content", "") for msg in output])

      if isinstance(gt, list):
            gt = " ".join([msg.get("content", "") for msg in gt])

      opt = parse_output(output)
      correct_option = parse_output(gt)

      # check reasoning similarity
      similarity = reasoning_similarity(output, gt)

      if len(output) > 60 and similarity > 0.6 and opt == str(correct_option):
          reward= 4
      elif opt != str(correct_option):
          reward= -1
      else:
          reward= 2
      rewards.append(reward)
    return rewards

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
# training the model through SFT
train_sft()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.69M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.35k [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/536M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/173 [00:00<?, ?B/s]

Applying LoRA to the model (PEFT)...

Map:   0%|          | 0/384 [00:00<?, ? examples/s]

Initializing SFTTrainer ...

Tokenizing train dataset:   0%|          | 0/307 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/307 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/77 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/77 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': 2, 'pad_token_id': 0}.

Starting SFT training...

SFT finished. Model saved to ./sft

In [ ]:
# Load fine-tuned SFT model
# sft_tokenizer = AutoTokenizer.from_pretrained("./sft/checkpoint-385")
# sft_model = AutoModelForCausalLM.from_pretrained("./sft/checkpoint-385").to("cuda")

sft_tokenizer = AutoTokenizer.from_pretrained(cfg.base_model)
sft_model = AutoModelForCausalLM.from_pretrained(
    cfg.base_model,
    torch_dtype="auto",
    device_map="auto",
    attn_implementation="eager").to("cuda")

# loading dataset
reward_dataset = init_reward_dataset()

# GRPO config
training_args = GRPOConfig(
    num_generations=4,
    output_dir=cfg.grpo_output_dir,
    per_device_train_batch_size=cfg.grpo_batch_size,
    learning_rate=cfg.grpo_learning_rate,
    lr_scheduler_type='linear',
    push_to_hub=False,
    # fp16 = True,
    report_to="none",
    num_train_epochs=cfg.grpo_epochs,
    gradient_accumulation_steps=2,
    logging_steps=10,
)

# Initialize the GRPO Trainer
trainer = GRPOTrainer(
    model=sft_model,
    processing_class=sft_tokenizer,
    reward_funcs=simple_reward_fn,
    args=training_args,
    train_dataset=reward_dataset["train"],
    eval_dataset=reward_dataset['test'],
)

# Start training
trainer.train()

Map:   0%|          | 0/384 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': 2, 'pad_token_id': 0}.

KeyboardInterrupt: